#!/bin/sh
#
# shutdown script for macOS 
#  This script is intended to serve as a better alternative to /sbin/shutdown
#  and /sbin/reboot.
#

readonly AS_QUIT_APPS='
set noQuit to {"Finder"} 

tell application "System Events"
	set appList to (name of processes where background only is false)
end tell

repeat with a in appList
	if a is not in noQuit then
        tell application a to quit
	end if
end repeat
'

readonly AS_CLOSE_FINDER='
tell application "Finder"
	close every window
end tell
'

readonly AS_SYSTEM_EVENTS_PREFIX='tell application "System Events" to'


usage() {
    echo "Usage: shutdown [-d|h|q|r|s]"
    printf "\t-a    Do not quit applications so that the reopen after shut down/reboot.\n"
    printf "\t-h    Halt/shut down the system.\n"
    printf "\t-q    Only quit all applications, will not shut down/reboot.\n"
    printf "\t-r    Reboot/restart the system.\n"

}


# do nothing when SIGHUP is received since we want to keep executing after
#  whatever terminal this script is called will likely be quit
trap '' SIGHUP


if [[ $# -eq 0 ]]; then
    usage
    exit 1
fi


app_state=false
debug=false
halt=false
quit=false
reboot=false

while getopts ":adqhr" opt; do
    case $opt in
        a) app_state=true;;
        d) debug=true;;
        h) halt=true;;
        q) quit=true;;
        r) reboot=true;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage
            exit 1
            ;;
    esac
done

if [[ "$OSTYPE" != "darwin"* ]]; then
    echo "This script is only supported on macOS." >&2
    exit 1
fi

if [[ "$halt" = true && "$reboot" == true ]]; then
    echo "Invalid options: -h and -r may not be used together." >&2
    exit 1
fi

if [[ "$quit" = true && "$halt" = true ]]; then
    echo "Invalid options: -q and -h may not be used together." >&2
    exit 1
fi

if [[ "$quit" = true && "$reboot" = true ]]; then
    echo "Invalid options: -q and -r may not be used together." >&2
    exit 1
fi

if [[ "$app_state" = true && "$quit" == true ]]; then
    echo "Invalid options: -a and -q may not be used together." >&2
    exit 1
fi

if [[ "$debug" = true ]]; then
    echo "app_state: $app_state"
    echo "halt: $halt"
    echo "quit: $quit"
    echo "reboot: $reboot"

    exit 0
fi


if [[ "$app_state" = false ]] ; then
    /usr/bin/osascript -e "$AS_QUIT_APPS"
    /usr/bin/osascript -e "$AS_CLOSE_FINDER"
fi

if [[ "$halt" = true ]]; then
    /usr/bin/osascript -e "$AS_SYSTEM_EVENTS_PREFIX shut down"
fi

if [[ "$reboot" = true ]]; then
    /usr/bin/osascript -e "$AS_SYSTEM_EVENTS_PREFIX restart"
fi
